# Generated by Django 5.2 on 2025-06-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_episode_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="episode_count",
        ),
    ]
